version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./static:/opt/proprietor/static
      - ./images:/opt/proprietor/images
    ports:
      - "8002:${NGINX_PORT}"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - app
  app:
    build: .
    environment:
      - DEBUG=${DEBUG}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./static:/opt/proprietor/static
      - ./images:/opt/proprietor/images
    entrypoint: /opt/proprietor/docker_entrypoint.sh
    expose:
      - 8000
    depends_on:
      - db
