# Generated by Django 4.0.3 on 2022-04-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ('floor', 'number')},
        ),
    ]
