# Generated by Django 4.0.3 on 2022-04-12 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_apartment_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utilitiesexpenses',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='utilitiesexpenses',
            constraint=models.UniqueConstraint(fields=('utility_type', 'bill_year', 'bill_month', 'apartment'), name='unique_type'),
        ),
    ]
