# Generated by Django 4.0.3 on 2022-03-21 21:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rooms_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('share', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=60)),
                ('block_number', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=10)),
                ('floors_count', models.IntegerField()),
                ('alias', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilitiesExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1981), django.core.validators.MaxValueValidator(2099)])),
                ('bill_month', models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'Jun'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True)),
                ('entry_dt', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.utilitytype')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(choices=[('Subscription', 'Subscription'), ('Rent', 'Rent'), ('Other', 'Other')], max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('deposit_date', models.DateField()),
                ('entry_dr', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(choices=[('Housekeeping', 'Housekeeping'), ('Planned', 'Planned'), ('Emergency', 'Emergency'), ('Salary', 'Salary'), ('Other', 'Other')], max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('entry_dr', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
    ]
