# Generated by Django 4.0.3 on 2022-04-12 20:09

from django.db import migrations, models
import proprietor.register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=9, validators=[proprietor.register.models.phone_validator]),
        ),
    ]
