# Generated by Django 4.0.3 on 2022-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_gender_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycodes',
            name='code',
            field=models.CharField(default='+359', max_length=6),
        ),
    ]
