# Generated by Django 4.0.3 on 2022-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_countrycodes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycodes',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
